// TrueAI — Secure Gemini API Proxy
// This file runs on Vercel's server — users can NEVER see this code or the key
// The GEMINI_KEY is stored in Vercel Environment Variables, never in any file
 
export default async function handler(req, res) {
  // Allow requests from your site only
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
 
  // Handle preflight
  if (req.method === 'OPTIONS') { res.status(200).end(); return; }
  if (req.method !== 'POST') { res.status(405).json({ error: 'Method not allowed' }); return; }
 
  // Get key from Vercel Environment Variables (secret — never visible to users)
  const GEMINI_KEY = process.env.GEMINI_KEY;
  if (!GEMINI_KEY) {
    res.status(500).json({ error: 'API key not configured on server' });
    return;
  }
 
  try {
    const { type, text, imageData } = req.body;
 
    let prompt = '';
    let parts = [];
 
    if (type === 'image') {
      // Image analysis
      prompt = `You are an AI image detection expert. Analyze if this image was generated by AI (Midjourney, DALL-E, Stable Diffusion) or is a real photograph.
 
Look for: unnatural textures, weird fingers/hands, inconsistent lighting, AI skin artifacts, too-perfect composition, background anomalies.
 
Respond ONLY in valid JSON (no markdown):
{"overall_score":<0-100>,"verdict":"<Likely Real Photo|Possibly AI-assisted|Likely AI-generated Image>","confidence":"<Low|Medium|High>","signals":{"text_patterns":{"score":<0-100>,"note":"<style observation>"},"structural":{"score":<0-100>,"note":"<lighting/shadow observation>"},"vocabulary":{"score":<0-100>,"note":"<texture observation>"},"style_consistency":{"score":<0-100>,"note":"<coherence observation>"}},"reasoning":"<2-3 sentences about what you observe>"}`;
 
      parts = [
        { inline_data: { mime_type: 'image/jpeg', data: imageData } },
        { text: prompt }
      ];
 
    } else {
      // Text analysis
      prompt = `You are an AI content detection expert. Analyze if this text is AI-generated or human-written.
 
Text:
"""
${(text || '').slice(0, 3000)}
"""
 
Respond ONLY in valid JSON (no markdown):
{"overall_score":<0-100>,"verdict":"<Likely Human|Possibly AI-assisted|Likely AI-generated>","confidence":"<Low|Medium|High>","signals":{"text_patterns":{"score":<0-100>,"note":"<1 sentence about buzzwords>"},"structural":{"score":<0-100>,"note":"<1 sentence about structure>"},"vocabulary":{"score":<0-100>,"note":"<1 sentence about word variety>"},"style_consistency":{"score":<0-100>,"note":"<1 sentence about tone>"}},"reasoning":"<2-3 sentences explaining the key signals>"}`;
 
      parts = [{ text: prompt }];
    }
 
    // Call Gemini API securely from server
    const geminiRes = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_KEY}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts }],
          generationConfig: { temperature: 0.1, maxOutputTokens: 800 }
        })
      }
    );
 
    if (!geminiRes.ok) {
      const err = await geminiRes.json();
      throw new Error(err.error?.message || 'Gemini API error');
    }
 
    const data = await geminiRes.json();
    const raw = data.candidates[0].content.parts[0].text
      .trim()
      .replace(/```json\n?|```/g, '')
      .trim();
 
    const result = JSON.parse(raw);
    res.status(200).json({
      overall: result.overall_score,
      verdict: result.verdict,
      confidence: result.confidence,
      signals: result.signals,
      reasoning: result.reasoning
    });
 
  } catch (err) {
    console.error('TrueAI API error:', err.message);
    res.status(500).json({ error: err.message || 'Analysis failed' });
  }
}
 


